
#Server Config Settings
[server]
	#The maximum number of text log entries allowed before old entries are deleted.
	#Lower if you encounter packet size problems.
	#Range: > 0
	logLimit = 100
	#Whether illegally broken traders (such as being replaced with /setblock, or modded machines that break blocks) will safely eject their block/contents into a temporary storage area for the owner to collect safely.
	#If disabled, illegally broken traders will throw their items on the ground, and can thus be griefed by modded machines.
	ejectIllegalBreaks = true
	#The maximum number of notifications each player can have before old entries are deleted.
	#Lower if you encounter packet size problems.
	#Range: > 0
	notificationLimit = 500
	#Determines whether or not coins should be craftable via the Coin Minting Machine.
	canMintCoins = false
	#Determines whether or not coins can be melted back into their source material in the Coin Minting Machine.
	canMeltCoins = true

	#Wallet Settings.
	[server.wallet]
		#The lowest level wallet capable of automatically collecting coins while equipped.
		#0-Copper Wallet; 1-Iron Wallet; 2-Gold Wallet; 3-Emerald Wallet; 4-Diamond Wallet; 5-Netherite Wallet
		#Range: 0 ~ 5
		pickupLevel = 2
		#The lowest level wallet capable of converting coins in the UI.
		#0-Copper Wallet; 1-Iron Wallet; 2-Gold Wallet; 3-Emerald Wallet; 4-Diamond Wallet; 5-Netherite Wallet
		#Must be less than or equal to 'pickupLevel'.
		#Range: 0 ~ 5
		convertLevel = 1
		#The lowest level wallet capable of allowing transfers to/from your bank account.
		#0-Copper Wallet; 1-Iron Wallet; 2-Gold Wallet; 3-Emerald Wallet; 4-Diamond Wallet; 5-Netherite Wallet
		#Range: 0 ~ 5
		bankLevel = 5

	#Specific Coin Melting Settings.
	[server.coin_melting]
		#Whether iron coins can be melted.
		canMeltIron = true
		#Whether copper coins can be melted.
		canMeltCopper = true
		#Whether emerald coins can be melted.
		canMeltEmerald = false
		#Whether netherite coins can be melted.
		canMeltNetherite = true
		#Whether gold coins can be melted.
		canMeltGold = true
		#Whether diamond coins can be melted.
		canMeltDiamond = true

	#Enchantment Settings
	[server.enchantments]
		#The base radius around the player that the Coin Magnet enchantment will collect coins from.
		#Range: 0 ~ 50
		coinMagnetRangeBase = 5
		#The cost required to repair a single item durability point with the Money Mending enchantment.
		moneyMendingCoinCost = "1-lightmanscurrency:coin_copper"
		#The increase in collection radius added by each additional level of the enchantment.
		#Range: 0 ~ 50
		coinMagnetRangeLevel = 2

	#Item Capacity Upgrade Settings
	[server.upgrades]
		#The amount of item storage added by the second Item Capacity upgrade (Gold).
		#Range: 1 ~ 1728
		upgradeCapacity2 = 384
		#The amount of item storage added by the third Item Capacity upgrade (Diamond).
		#Range: 1 ~ 1728
		upgradeCapacity3 = 576
		#The amount of item storage added by the first Item Capacity upgrade (Iron).
		#Range: 1 ~ 1728
		upgradeCapacity1 = 192

	#Discord bot settings. Requires lightmansdiscord v0.0.3.0+ to use.
	[server.discord]
		#Prefix for currency commands.
		prefix = "!"
		#Whether the !search command should limit its search results to only Network Traders, or if it should list all traders.
		limitSearchToNetwork = true
		#The channel where users can run the currency commands and where currency related announcements will be made.
		channel = "000000000000000000"

		#Bot notification options.
		[server.discord.notifications]
			#Whether a notification will appear in the currency bot channel when an Auction is completed and had a bidder.
			auctionHouseWon = true
			#Whether a notification will appear in the currency bot channel when a Network Trader is created.
			#Notification will have a 60 second delay to allow them time to customize the traders name, etc.
			networkTraderBuilt = true
			#Whether a notification will appear in the currency bot channel when an Auction is cancelled in the Auction House.
			auctionHouseCancelled = false
			#Whether a notification will appear in the currency bot channel when an Auction is created in the Auction House.
			auctionHouseCreated = true
			#Whether a notification will appear in the currency bot channel when a Persistent Auction is created automatically.
			#Requires that auction house creation notifications also be enabled.
			auctionHousePersistentCreations = true

	#Coin value display settings.
	[server.coin_value_display]
		#Input method used for the Coin Value Input.
		#DEFAULT: Default coin input with up/down buttons for each coin type.
		#VALUE: Text box input for the coins display value.
		#Allowed Values: DEFAULT, VALUE
		coinValueInputType = "DEFAULT"
		#Coin item defined as 1 value unit for display purposes. Any coins worth less than the base coin will have a decimal value.
		baseValueCoin = "lightmanscurrency:coin_copper"
		#Value display method used throughout the mod.
		#DEFAULT: Coin Count & Icon aglomerate (1n5g for 1 netherite and 5 gold)
		#VALUE: Coin numerical display value as defined by the baseValueCoin and valueFormat config options below.
		#Allowed Values: DEFAULT, VALUE
		coinValueType = "DEFAULT"
		#Value display format. Used to add currency signs to coin value displays.
		#{value} will be replaced with the coins numerical value. Only 1 should be present at any given time.
		valueFormat = "${value}"
		#Tooltip type displayed on coin items.
		#DEFAULT: Conversion tooltips, explaining it's value based on the coins it can be converted to/from.
		#VALUE: Coins numerical display value as defined by the coinValueType option below. Not recommend if using the DEFAULT coinValueType.
		#Allowed Values: DEFAULT, VALUE, NONE
		coinTooltipType = "DEFAULT"

	#Player Trading Options
	[server.player_trading]
		#The maximum distance allowed between players in order for a player trade to persist.
		#-1 will always allow trading regardless of dimension.
		#0 will allow infinite distance but require that both players be in the same dimension.
		#Range: -1.0 ~ 1.7976931348623157E308
		maxPlayerDistance = -1.0

	#Specific Coin Minting Settings.
	[server.coin_minting]
		#Whether diamond coins can be minted.
		canMintDiamond = false
		#Whether copper coins can be minted.
		canMintCopper = false
		#Whether emerald coins can be minted.
		canMintEmerald = false
		#Whether iron coins can be minted.
		canMintIron = false
		#Whether netherite coins can be minted.
		canMintNetherite = false
		#Whether gold coins can be minted.
		canMintGold = false

	#Auction House Settings
	[server.auction_house]
		#The minimum number of days an auction can be carried out.
		#Range: > 0
		minDuration = 0
		#Whether the Auction House will appear in the trading terminal.
		#If false, you will only be able to access the Auction House from an Auction Stand.
		visibleOnTerminal = true
		#Whether the Auction House will be automatically generated and accessible.
		#If disabled after players have interacted with it, items & money in the auction house cannot be accessed until re-enabled.
		#If disabled, it is highly recommended that you also disable the 'crafting.allowAuctionStandCrafting' option in the common config.
		enabled = true
		#The maximum number of days an auction can be carried out.
		#Range: > 1
		maxDuration = 30

