
#Client configuration settings
[client]

	#Notification Settings
	[client.notification]
		#Whether notifications should be posted in your chat when you receive them.
		notificationsInChat = true

	#Sound Settings
	[client.sounds]
		#Whether Money Mending should make a noise when triggered.
		moneyMendingClink = true

	#Time Formatting Settings
	[client.time]
		#How Notification Timestamps are displayed.
		#Follows SimpleDateFormat formatting: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
		timeFormatting = "MM/dd/yy hh:mmaa"

	#Wallet Slot Settings
	[client.wallet_slot]
		#The offset that the wallet button should be placed at relative to the wallet slot position.
		#Range: -1000 ~ 1000
		buttonX = 8
		#Range: -1000 ~ 1000
		buttonY = -10
		#The position that the wallet slot will be placed at in the players creative inventory.
		#Range: -1000 ~ 1000
		creativeSlotX = 126
		#Range: -1000 ~ 1000
		slotY = 7
		#Range: -1000 ~ 1000
		creativeSlotY = 19
		#The position that the wallet slot will be placed at in the players inventory.
		#Range: -1000 ~ 1000
		slotX = 76

	#Quality Settings
	[client.quality]
		#Maximum number of items each Item Trader can render (per-trade) as stock. Lower to decrease client-lag in trader-rich areas.
		#Setting to 0 will disable item rendering entirely, so use with caution.
		#Range: > 0
		itemTraderRenderLimit = 2147483647

	#Inventory Button Settings
	[client.inventory_buttons]
		#The x position that the notification & team manager buttons will be placed at in the players inventory.
		#Range: > -2147483648
		buttonX = 152
		#The x position that the notification & team manager buttons will be placed at in the players inventory.
		#Range: > -2147483648
		buttonY = 3
		#The x position that the notification & team manager buttons will be placed at in the players creative inventory.
		#Range: > -2147483648
		buttonCreativeX = 171
		#The y position that the notification & team manager buttons will be placed at in the players creative inventory.
		#Range: > -2147483648
		buttonCreativeY = 18

