
#Configuration file for player states.
#You can adjust stamina delta (negative value means consumption / positive value means gain) and
#recovery delay (in ticks) of all player states registered in the game.
#To reload the config, use the following command: /paraglider reloadPlayerStates
#
[paraglider]

	[paraglider.running]
		#Range: > 0
		recoveryDelay = 10
		#Range: > -2147483648
		staminaDelta = -10

	[paraglider.breathing_underwater]
		#Range: > 0
		recoveryDelay = 0
		#Range: > -2147483648
		staminaDelta = 20

	[paraglider.swimming]
		#Range: > 0
		recoveryDelay = 10
		#Range: > -2147483648
		staminaDelta = -6

	[paraglider.paragliding]
		#Range: > 0
		recoveryDelay = 10
		#Range: > -2147483648
		staminaDelta = -3

	[paraglider.midair]
		#Range: > 0
		recoveryDelay = 0
		#Range: > -2147483648
		staminaDelta = 0

	[paraglider.panic_paragliding]
		#Range: > 0
		recoveryDelay = 10
		#Range: > -2147483648
		staminaDelta = -3

	[paraglider.idle]
		#Range: > 0
		recoveryDelay = 0
		#Range: > -2147483648
		staminaDelta = 20

	[paraglider.flying]
		#Range: > 0
		recoveryDelay = 0
		#Range: > -2147483648
		staminaDelta = 20

	[paraglider.underwater]
		#Range: > 0
		recoveryDelay = 0
		#Range: > -2147483648
		staminaDelta = 3

	[paraglider.ascending]
		#Range: > 0
		recoveryDelay = 10
		#Range: > -2147483648
		staminaDelta = -3

	[paraglider.on_vehicle]
		#Range: > 0
		recoveryDelay = 0
		#Range: > -2147483648
		staminaDelta = 20

