messages:
  plugin-load-error: "{0}の読み込み中にエラーが発生しました: "
  non-player-execution: "コンソールからそのコマンドは実行できません。"
  incorrect-argument: "コマンドの引数が正しくありません。"
  integer-less: "この整数は{0}以上でなくてはならないため、{1}は適しません。"
  invalid-integer: "「{0}」は無効な整数です。"
  pos-not-exist: "接続点 {0} は存在しません。"
  problem-here: "←［問題箇所］"
  pos-N: "接続点 {0}"
  pos-Nf: "制御点 {0}f"
  pos-Nb: "制御点 {0}b"
  pos-set: "{0} を {1} に設定しました。"
  pos-clear: "{0} を削除しました。"
  pos-clear-all: "全てのPosを削除しました。"
  pos-remove: "接続点 {0} を取り除きました。"
  pos-shift: "posをシフトしました。"
  bc-changed: "{0} 個のブロックが変更されました。//undo で元に戻します。"
  bc-length: "曲線の長さ: {0} ブロック (推定)"
  incomplete-region: "領域を選択してください。"
  incomplete-pos: "始点を選択してください。"
  max-changed-blocks: "変更できるブロックの最大値は ({0}) に設定されています。"
  max-set-length: "設定できる曲線の最大長は ({0}) に設定されています。"
  max-pos-value: "設定できるposの最大値は ({0}) に設定されています。"