messages:
  plugin-load-error: "載入 {0} 時發生錯誤："
  non-player-execution: "無法在主控台執行此指令。"
  incorrect-argument: "無效的指令參數。"
  integer-less: "整數不能小於 {0}，而輸入值為 {1}。"
  invalid-integer: "無效的整數 '{0}'。"
  pos-not-exist: "Connection point {0} does not exist."
  problem-here: "<--[此處]"
  pos-N: "連接位置 {0}"
  pos-Nf: "控制位置 {0}f"
  pos-Nb: "控制位置 {0}b"
  pos-set: "已設定 {0} 為 {1}。"
  pos-clear: "已刪除 {0}。"
  pos-clear-all: "已刪除所有位置。"
  pos-remove: "Removed connection point {0}."
  pos-shift: "Pos shifted."
  bc-changed: "{0} 個方塊已更改。使用 //undo 指令可復原"
  bc-length: "曲線長度：{0} 個方塊（估計）"
  incomplete-region: "請先選擇一個區域。"
  incomplete-pos: "請先選擇起始位置。"
  max-changed-blocks: "達到操作中的最大方塊更改數量限制（{0}）。"
  max-set-length: "達到操作中的最大曲線長度限制（{0}）。"
  max-pos-value: "達到操作中的最大位置值限制（{0}）。"
